[package]
name = "multi-whatsapp"
version = "1.1.0"
description = "Multi tab WhatsApp desktop client"
authors = ["Syahda Fahreza"]
edition = "2021"

[lib]
name = "multi_whatsapp_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-shell = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-notification = "2"
tauri-plugin-autostart = "2"
tauri-plugin-clipboard-manager = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
open = "5.3"
